apiVersion: v2
name: hyperfleet-adapter
description: hyperfleet-adapter deployment from external GitHub repository
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: hyperfleet-adapter
    version: "1.0.0"
    repository: https://cdoan1.github.io/regional-charts
