apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperfleet-adapter.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hyperfleetAdapter.service.type }}
  ports:
  - port: {{ .Values.hyperfleetAdapter.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.hyperfleetAdapter.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "hyperfleet-adapter.selectorLabels" . | nindent 4 }}
