{{- if .Values.hyperfleetAdapter.broker.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperfleet-adapter.brokerConfigMapName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker-config
    hyperfleet.io/broker-type: {{ .Values.hyperfleetAdapter.broker.type }}
data:
  broker.yaml: |
    broker:
      type: {{ .Values.hyperfleetAdapter.broker.type }}
      {{- if eq .Values.hyperfleetAdapter.broker.type "rabbitmq" }}
      rabbitmq:
        url: {{ .Values.hyperfleetAdapter.broker.rabbitmq.url | quote }}
        queue: {{ .Values.hyperfleetAdapter.broker.rabbitmq.queue | quote }}
        exchange: {{ .Values.hyperfleetAdapter.broker.rabbitmq.exchange | quote }}
        routingKey: {{ .Values.hyperfleetAdapter.broker.rabbitmq.routingKey | quote }}
      {{- end }}
    subscriber:
      parallelism: 1
{{- end }}
