{{- if .Values.hyperfleetApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperfleet-api.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hyperfleet-api.labels" . | nindent 4 }}
  {{- with .Values.hyperfleetApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
