{{- if .Values.hyperfleetSystem.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: {{ .Values.hyperfleetSystem.namespace }}
  labels:
    {{- include "hyperfleet-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  username: {{ .Values.hyperfleetSystem.postgresql.database.username }}
  password: {{ .Values.hyperfleetSystem.postgresql.database.password | default (include "hyperfleet-system.randomPassword" .) }}
  database: {{ .Values.hyperfleetSystem.postgresql.database.name }}
{{- end }}
