{{- if .Values.hyperfleetSystem.rabbitmq.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.hyperfleetSystem.namespace }}
  labels:
    {{- include "hyperfleet-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  username: {{ .Values.hyperfleetSystem.rabbitmq.auth.username }}
  password: {{ .Values.hyperfleetSystem.rabbitmq.auth.password | default (include "hyperfleet-system.randomPassword" .) }}
  erlang-cookie: {{ .Values.hyperfleetSystem.rabbitmq.auth.erlangCookie | default (include "hyperfleet-system.randomPassword" .) }}
{{- end }}
