{{- if .Values.hyperfleetSentinel.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
  {{- with .Values.hyperfleetSentinel.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
