{{- if .Values.hyperfleetSystem.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperfleet-system.serviceAccountName" . }}
  namespace: {{ .Values.hyperfleetSystem.namespace }}
  labels:
    {{- include "hyperfleet-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
{{- end }}
