apiVersion: v2
name: argocd
description: ArgoCD deployment via dependency
type: application
version: 1.0.0
dependencies:
  - name: argo-cd
    version: "9.3.4"
    repository: https://argoproj.github.io/argo-helm