# TODO: Replace this with direct access to avoid having a secret at all
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "maestro-server.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-server.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    # Enable Pod Identity authentication (no IRSA/OIDC needed)
    usePodIdentity: "true"
    region: {{ .Values.aws.region | default "us-east-1" }}
    objects: |
      - objectName: {{ .Values.externalSecrets.dbCredentialsSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db.user"
          - path: "password"
            objectAlias: "db.password"
          - path: "host"
            objectAlias: "db.host"
          - path: "port"
            objectAlias: "db.port"
          - path: "database"
            objectAlias: "db.name"
      - objectName: {{ .Values.externalSecrets.mqttCertSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "certificate"
            objectAlias: "certificate"
          - path: "privateKey"
            objectAlias: "privateKey"
          - path: "caCert"
            objectAlias: "ca.crt"
