apiVersion: v2
name: hyperfleet-api
description: hyperfleet-api deployment from external GitHub repository
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: hyperfleet-api
    version: "1.0.0"
    repository: https://cdoan1.github.io/regional-charts
