{{- $bootstrapCM := lookup "v1" "ConfigMap" "kube-system" "bootstrap-output" }}
{{- $clusterName := "" }}
{{- if $bootstrapCM }}
{{- $clusterName = index $bootstrapCM.data "cluster_name" }}
{{- else if .Values.clusterName }}
{{- $clusterName = .Values.clusterName }}
{{- else }}
{{- fail "Unable to determine cluster name. ConfigMap kube-system/bootstrap-output not found and clusterName not provided in values" }}
{{- end }}
{{- $dbSecretName := printf "%s/maestro/db-credentials" $clusterName }}
{{- $mqttSecretName := printf "%s/maestro/server-mqtt-cert" $clusterName }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "maestro-server-eso.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-server-eso.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    # Enable Pod Identity authentication (no IRSA/OIDC needed)
    usePodIdentity: "true"
    region: {{ .Values.aws.region | default "us-east-1" }}
    objects: |
      - objectName: {{ $dbSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db.user"
          - path: "password"
            objectAlias: "db.password"
          - path: "host"
            objectAlias: "db.host"
          - path: "port"
            objectAlias: "db.port"
          - path: "database"
            objectAlias: "db.name"
      - objectName: {{ $mqttSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "certificate"
            objectAlias: "certificate"
          - path: "privateKey"
            objectAlias: "privateKey"
          - path: "caCert"
            objectAlias: "ca.crt"
